apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - port: 8000
      targetPort: 8000
      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-pods-deployment
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: ronibay/my_repo:weatherapp
        ports:	
        - containerPort: 8000
