apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "weather-app" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort | default "null" }}
